"""Runtime JSON contract schemas for the first deterministic pipeline."""

from __future__ import annotations

from typing import Any


OBJECT: dict[str, Any] = {"type": "object"}
STRING: dict[str, Any] = {"type": "string"}
INTEGER: dict[str, Any] = {"type": "integer"}
NUMBER: dict[str, Any] = {"type": "number"}
ARRAY: dict[str, Any] = {"type": "array"}


SCHEMAS: dict[str, dict[str, Any]] = {
    "episode_plan": {
        "type": "object",
        "required": [
            "schema_version",
            "pipeline_version",
            "project_id",
            "episode_id",
            "title",
            "language",
            "target_duration_seconds",
            "scenes",
            "validation_status",
        ],
        "properties": {
            "schema_version": {"type": "string", "const": "1.0"},
            "pipeline_version": STRING,
            "project_id": STRING,
            "episode_id": STRING,
            "title": STRING,
            "language": STRING,
            "target_duration_seconds": INTEGER,
            "scenes": {
                "type": "array",
                "minItems": 1,
                "items": {
                    "type": "object",
                    "required": ["scene_id", "order", "title", "estimated_duration_seconds"],
                    "properties": {
                        "scene_id": STRING,
                        "order": INTEGER,
                        "title": STRING,
                        "estimated_duration_seconds": INTEGER,
                    },
                },
            },
            "validation_status": STRING,
        },
    },
    "scene_prompts": {
        "type": "object",
        "required": [
            "schema_version",
            "pipeline_version",
            "project_id",
            "episode_id",
            "language",
            "prompt_style_version",
            "prompts",
            "scenes",
            "validation_status",
        ],
        "properties": {
            "schema_version": {"type": "string", "const": "1.0"},
            "pipeline_version": STRING,
            "project_id": STRING,
            "episode_id": STRING,
            "language": STRING,
            "prompt_style_version": STRING,
            "prompts": {
                "type": "array",
                "minItems": 1,
                "items": {
                    "type": "object",
                    "required": [
                        "scene_id",
                        "order",
                        "image_prompt",
                        "animation_prompt",
                        "voice_prompt",
                        "music_prompt",
                        "negative_prompt",
                        "character_references",
                        "world_references",
                        "output_targets",
                    ],
                    "properties": {
                        "scene_id": STRING,
                        "order": INTEGER,
                        "image_prompt": STRING,
                        "animation_prompt": STRING,
                        "voice_prompt": STRING,
                        "music_prompt": STRING,
                        "negative_prompt": STRING,
                        "character_references": ARRAY,
                        "world_references": ARRAY,
                        "output_targets": OBJECT,
                    },
                },
            },
            "scenes": ARRAY,
            "validation_status": STRING,
        },
    },
    "image_manifest": {
        "type": "object",
        "required": [
            "project",
            "episode",
            "task_id",
            "image_director_version",
            "source_scene_prompts",
            "total_scenes",
            "image_status",
            "scenes",
            "validation_notes",
            "metadata",
        ],
        "properties": {
            "project": STRING,
            "episode": STRING,
            "task_id": STRING,
            "image_director_version": STRING,
            "source_scene_prompts": STRING,
            "total_scenes": INTEGER,
            "image_status": {"type": "string", "enum": ["planned_not_generated"]},
            "scenes": {"type": "array", "minItems": 1, "items": OBJECT},
            "validation_notes": ARRAY,
            "metadata": OBJECT,
        },
    },
    "voice_manifest": {
        "type": "object",
        "required": [
            "project",
            "episode",
            "task_id",
            "voice_director_version",
            "source_episode_script",
            "source_scene_prompts",
            "source_image_manifest",
            "total_scenes",
            "audio_status",
            "scenes",
            "validation_notes",
            "metadata",
        ],
        "properties": {
            "project": STRING,
            "episode": STRING,
            "task_id": STRING,
            "voice_director_version": STRING,
            "source_episode_script": STRING,
            "source_scene_prompts": STRING,
            "source_image_manifest": STRING,
            "total_scenes": INTEGER,
            "audio_status": {"type": "string", "enum": ["planned_not_generated"]},
            "scenes": {"type": "array", "minItems": 1, "items": OBJECT},
            "validation_notes": ARRAY,
            "metadata": OBJECT,
        },
    },
    "video_manifest": {
        "type": "object",
        "required": [
            "project",
            "episode",
            "task_id",
            "video_editor_version",
            "source_episode_script",
            "source_scene_prompts",
            "source_image_manifest",
            "source_voice_manifest",
            "total_scenes",
            "total_estimated_duration_seconds",
            "render_status",
            "planned_final_output_file",
            "scenes",
            "validation_notes",
            "metadata",
        ],
        "properties": {
            "project": STRING,
            "episode": STRING,
            "task_id": STRING,
            "video_editor_version": STRING,
            "source_episode_script": STRING,
            "source_scene_prompts": STRING,
            "source_image_manifest": STRING,
            "source_voice_manifest": STRING,
            "total_scenes": INTEGER,
            "total_estimated_duration_seconds": INTEGER,
            "render_status": {"type": "string", "enum": ["planned_not_rendered"]},
            "planned_final_output_file": STRING,
            "scenes": {"type": "array", "minItems": 1, "items": OBJECT},
            "validation_notes": ARRAY,
            "metadata": OBJECT,
        },
    },
    "episode_report": {
        "type": "object",
        "required": [
            "schema_version",
            "pipeline_version",
            "project",
            "episode",
            "task_id",
            "analytics_version",
            "pipeline_status",
            "source_artifacts",
            "stage_summary",
            "generation_summary",
            "artifact_status",
            "validation_summary",
            "models_used",
            "prompt_versions",
            "cost_summary",
            "metadata",
        ],
        "properties": {
            "schema_version": {"type": "string", "const": "1.0"},
            "pipeline_version": STRING,
            "project": STRING,
            "episode": STRING,
            "task_id": STRING,
            "analytics_version": STRING,
            "pipeline_status": STRING,
            "source_artifacts": OBJECT,
            "stage_summary": OBJECT,
            "generation_summary": OBJECT,
            "artifact_status": OBJECT,
            "validation_summary": OBJECT,
            "models_used": ARRAY,
            "prompt_versions": OBJECT,
            "cost_summary": OBJECT,
            "metadata": OBJECT,
        },
    },
    "metadata": {
        "type": "object",
        "required": [
            "schema_version",
            "pipeline_version",
            "project_id",
            "episode_id",
            "title",
            "language",
            "target_platform",
            "duration_seconds",
            "created_at",
            "pipeline_status",
            "artifact_paths",
            "source_contracts",
            "agents",
            "models_used",
            "prompt_versions",
            "generation_summary",
            "validation_summary",
            "archive_policy",
        ],
        "properties": {
            "schema_version": {"type": "string", "const": "1.0"},
            "pipeline_version": STRING,
            "project_id": STRING,
            "episode_id": STRING,
            "title": STRING,
            "language": STRING,
            "target_platform": STRING,
            "duration_seconds": {"type": ["integer", "null"]},
            "created_at": STRING,
            "pipeline_status": {"type": "string", "enum": ["draft", "in_progress", "completed", "failed", "archived"]},
            "artifact_paths": {
                "type": "object",
                "required": ["video", "script", "prompts", "report", "images", "voice", "subtitles"],
                "properties": {
                    "video": STRING,
                    "script": STRING,
                    "prompts": STRING,
                    "report": STRING,
                    "images": STRING,
                    "voice": STRING,
                    "subtitles": STRING,
                },
            },
            "source_contracts": OBJECT,
            "agents": ARRAY,
            "models_used": ARRAY,
            "prompt_versions": OBJECT,
            "generation_summary": OBJECT,
            "validation_summary": OBJECT,
            "archive_policy": OBJECT,
        },
    },
}
